# Generated by Django 5.0.6 on 2024-08-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
