# Generated by Django 5.0.6 on 2024-08-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_alter_entry_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='unique_number',
        ),
    ]
