# Generated by Django 5.0.6 on 2024-08-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_remove_entry_unique_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='progress',
            field=models.CharField(default='In Progress', max_length=50),
        ),
    ]
